In [209]:
import numpy as np
import timeit


ModuleNotFoundError: No module named 'Tester'

In [ ]:
#array[start=0:stop=len(arrray)-1:step=1]

In [2]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
variants = [ a[0:5:1], a[0:5], a[:5]]
variants

[array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4])]

In [11]:
variants = [ a[slice(0, 5, 1)], a[slice(0,5)], a[slice(5)]]
variants           

[array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4])]

In [12]:
variants = [ a[0:len(a):2], a[0::2], a[::2]]
variants   

[array([ 0,  2,  4,  6,  8, 10, 12, 14]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14])]

In [14]:
variants = [ a[1:len(a):2], a[1::2] ]
variants   

[array([ 1,  3,  5,  7,  9, 11, 13]), array([ 1,  3,  5,  7,  9, 11, 13])]

In [15]:
variants = [ a[3:12:3], a[3:-3:3]]
variants   

[array([3, 6, 9]), array([3, 6, 9])]

In [16]:
variants = [ a[1:len(a):2], a[1::2] ]
variants   

[array([ 1,  3,  5,  7,  9, 11, 13]), array([ 1,  3,  5,  7,  9, 11, 13])]

In [17]:
variants = [ a[3:13:3][::-1], a[12:2:-3], a[-3:2:-3]]
variants   

[array([12,  9,  6,  3]), array([12,  9,  6,  3]), array([12,  9,  6,  3])]

In [21]:
a = np.array ([1,2,3,4,5])
mask = np.array ([False, True, True, False, True]),
mask, a, a[mask]

((array([False,  True,  True, False,  True]),),
 array([1, 2, 3, 4, 5]),
 array([2, 3, 5]))

In [24]:
np.random.seed (1024)

a = np.random.randint (-2,7,34)
a

array([-1, -1,  3, -1, -2, -2,  1,  0, -2,  5,  6,  5, -1,  0,  1,  3, -2,
        3,  3,  1, -2,  4,  4,  3,  4,  2,  2, -1, -2, -1,  6,  5, -2, -1])

In [25]:
a [a < 0]

array([-1, -1, -1, -2, -2, -2, -1, -2, -2, -1, -2, -1, -2, -1])

In [26]:
variants = [a[a % 3 == 0],
           a[np.logical_not(a % 3)],
           a[~((a % 3).astype(bool))]]
variants

[array([3, 0, 6, 0, 3, 3, 3, 3, 6]),
 array([3, 0, 6, 0, 3, 3, 3, 3, 6]),
 array([3, 0, 6, 0, 3, 3, 3, 3, 6])]

In [27]:
np.random.seed(1024)

a = np.random.randint(0, 9, 23)
a

array([1, 1, 5, 1, 0, 0, 3, 2, 0, 7, 8, 7, 1, 2, 3, 5, 0, 5, 5, 3, 0, 6,
       6])

In [30]:
mask_3 = a % 3 == 0
mask_5 = a % 5 == 0

variants = [a[np.logical_or (mask_3, mask_5)],
            a[mask_3 | mask_5]]

mask_3, mask_5, variants

(array([False, False, False, False,  True,  True,  True, False,  True,
        False, False, False, False, False,  True, False,  True, False,
        False,  True,  True,  True,  True]),
 array([False, False,  True, False,  True,  True, False, False,  True,
        False, False, False, False, False, False,  True,  True,  True,
         True, False,  True, False, False]),
 [array([5, 0, 0, 3, 0, 3, 5, 0, 5, 5, 3, 0, 6, 6]),
  array([5, 0, 0, 3, 0, 3, 5, 0, 5, 5, 3, 0, 6, 6])])

In [31]:
mask = np.array ([False, True, True, False, True])

mask, np.where(mask
              )

(array([False,  True,  True, False,  True]), (array([1, 2, 4], dtype=int64),))

In [32]:
np.where(a > 0)

(array([ 0,  1,  2,  3,  6,  7,  9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 21,
        22], dtype=int64),)

In [33]:
a [np.where (a > 0)]

array([1, 1, 5, 1, 3, 2, 7, 8, 7, 1, 2, 3, 5, 5, 5, 3, 6, 6])

In [4]:
np.sqrt(np.arange(3))


array([0.        , 1.        , 1.41421356])

In [6]:
np.sqrt(2)

1.4142135623730951

In [8]:
a = np.array(
    [
            [
                
                [ 0,  1,  2,   3],
                [ 4,  5,  6,   7],
                [ 8,  9,  10, 11]
            ],
            [   [ 12, 13, 14, 15],
                [ 16, 17, 18, 19],
                [ 20, 21, 22, 23]
            ],
            [   [ 24, 25, 26, 27],
                [ 28, 29, 30, 31],
                [ 32, 33, 34, 35]
            ],
            [   [ 36, 37, 38, 39],
                [ 40, 41, 42, 43],
                [ 44, 45, 46, 47]
            ],
    ])
a, a.shape, a.ndim, a.dtype

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],
 
        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]],
 
        [[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]]),
 (4, 3, 4),
 3,
 dtype('int32'))

In [10]:
a = np.arange(30).reshape(5,-1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [12]:
a [0][0], a[0][2], a[-1][-2], a[0]

(0, 2, 28, array([0, 1, 2, 3, 4, 5]))

In [14]:
a [0,0], a[0,2], a[-1,-2], a[0]

(0, 2, 28, array([0, 1, 2, 3, 4, 5]))

In [15]:
variants = [ a [2], a[2,:]]
variants

[array([12, 13, 14, 15, 16, 17]), array([12, 13, 14, 15, 16, 17])]

In [16]:
a[:,3]

array([ 3,  9, 15, 21, 27])

In [17]:
a[:,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [18]:
a[0,1::2]

array([1, 3, 5])

In [21]:
a, a[1::2,2::3][::-1]

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[20, 23],
        [ 8, 11]]))

In [24]:
a = np.arange(30).reshape(5,-1)
a, a[[ 2, 4, 3]]

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[12, 13, 14, 15, 16, 17],
        [24, 25, 26, 27, 28, 29],
        [18, 19, 20, 21, 22, 23]]))

In [26]:
a, a[:, [0, -1]]

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[ 0,  5],
        [ 6, 11],
        [12, 17],
        [18, 23],
        [24, 29]]))

In [29]:
a, a[[ 2, 4, 3]][:, [0, -1]]

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[12, 17],
        [24, 29],
        [18, 23]]))

In [32]:
a = np.arange(24).reshape(2,3,4)
a, a[...,0], a[:,:,0]

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[ 0,  4,  8],
        [12, 16, 20]]),
 array([[ 0,  4,  8],
        [12, 16, 20]]))

In [33]:
a, a[1,...], a[0,:,:]

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [34]:
a, a[..., 0,:]

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]))

In [81]:
a = np.arange(12).reshape(2,6).astype(float) 
a += 1
a

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]])

In [57]:
count = a.size
count

12

In [58]:
item_size = a.dtype.itemsize
print (item_size)
item_size

8


8

In [59]:
array_size = count * item_size
print (array_size)
print (a.nbytes)

96
96


In [60]:
a,  a.strides

(array([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]]),
 (48, 8))

In [61]:
b = a
b

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]])

In [62]:
a = np.array([1,2,3,4,5], dtype=np.float32)

In [67]:
b = np.asarray(a)
b

array([ 1.,  2., -2.,  4.,  5.], dtype=float32)

In [66]:
c = np.array(a)

a[2] = -2

a, c

(array([ 1.,  2., -2.,  4.,  5.], dtype=float32),
 array([1., 2., 3., 4., 5.], dtype=float32))

In [77]:
b = 0
b = np.asarray(a, dtype = np.int32)
a[1] = -1000
a,b


(array([    1., -1000.,    -2.,     4.,     5.], dtype=float32),
 array([    1, -1000,    -2,     4,     5]))

In [78]:
a = np.array([1,2,3,4,5], dtype=np.float32)
b = a.view(np.int32)
a[2] = -2

a,b


(array([ 1.,  2., -2.,  4.,  5.], dtype=float32),
 array([ 1065353216,  1073741824, -1073741824,  1082130432,  1084227584]))

In [82]:
b = a.reshape(6,2)

b, b.shape, b.strides

(array([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]),
 (6, 2),
 (16, 8))

In [84]:
c = a.reshape(3,2,2)
c, c.shape,c.strides

(array([[[ 1.,  2.],
         [ 3.,  4.]],
 
        [[ 5.,  6.],
         [ 7.,  8.]],
 
        [[ 9., 10.],
         [11., 12.]]]),
 (3, 2, 2),
 (32, 16, 8))

In [86]:
a.reshape(-1,3)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [89]:
b = a.reshape(3,-1)
a [0,1] = -10
b,a

(array([[  1., -10.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]]),
 array([[  1., -10.,   3.,   4.,   5.,   6.],
        [  7.,   8.,   9.,  10.,  11.,  12.]]))

In [91]:
b = a.flatten()
a[0,1] = -20
b

array([  1., -20.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.])

In [92]:
b = a.ravel()
a[0,1] =  -30
b

array([  1., -30.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.])

In [95]:
c = a.T
a[0,1] = -40
c, c.shape,c.strides

(array([[  1.,   7.],
        [-40.,   8.],
        [  3.,   9.],
        [  4.,  10.],
        [  5.,  11.],
        [  6.,  12.]]),
 (6, 2),
 (8, 48))

In [96]:
b = np.arange(10)

b, b.shape, b.strides

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), (10,), (4,))

In [98]:
#a = b [np.newaxis, :]
a = a.reshape(1,*b.shape)
b[2] = -20

b,a

(array([  0,   1, -20,   3,   4,   5,   6,   7,   8,   9]),
 array([[  0,   1, -20,   3,   4,   5,   6,   7,   8,   9]]))

In [ ]:
a = a.reshape(3,-1)


In [111]:
a = np.zeros(shape=(3,2))
a, a.shape

(array([[0., 0.],
        [0., 0.],
        [0., 0.]]),
 (3, 2))

In [114]:
b = np.zeros_like(a)
a[0][1] = -0.1
b, b.shape, a, a.shape


(array([[0., 0.],
        [0., 0.],
        [0., 0.]]),
 (3, 2),
 array([[ 0. , -0.1],
        [ 0. ,  0. ],
        [ 0. ,  0. ]]),
 (3, 2))

In [116]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [123]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [119]:
np.arange (1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
np.arange (1, 10, 2) #шаг

array([1, 3, 5, 7, 9])

In [121]:
np.arange (1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [122]:
np.linspace(0, 1, 5, endpoint=True)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [125]:
a = np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [126]:
a ** 3 #np.power

array([[  0,   1,   8,  27,  64],
       [125, 216, 343, 512, 729]], dtype=int32)

In [127]:
a + 2 #np.add

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [128]:
2 * a # np.multiply

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [129]:
2 ** a #np.power

array([[  1,   2,   4,   8,  16],
       [ 32,  64, 128, 256, 512]], dtype=int32)

In [130]:
np.sqrt (a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [131]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [132]:
np.log(1+a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [133]:
np.log2(1+a)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809]])

In [134]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [135]:
np.greater (a, 0)

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [139]:
np.random.seed(128)
a = np.random.randint(0, 10, size=(7, ))
a [3] = 10
a

array([ 2,  3,  5, 10,  7,  2,  4])

In [140]:
a.min(), a.max(), a.argmax(), a.sum(), a.prod(), a.mean()

(2, 10, 3, 33, 16800, 4.714285714285714)

In [141]:
np.min(a), np.max(a), np.argmax(a), np.sum(a), np.prod(a), np.mean(a)

(2, 10, 3, 33, 16800, 4.714285714285714)

In [142]:
np.random.seed(16)

a = np.random.randint(0, 10, size=(4,4))
a [2,2] = 25
a

array([[ 9,  9,  5,  1],
       [ 4,  4,  9,  0],
       [ 0,  8, 25,  4],
       [ 0,  1,  2,  4]])

In [143]:
a.argmax()

10

In [144]:
a.ravel()[a.argmax()]

25

In [149]:
i = np.argmax(a)
i, j = i // a.shape[1], i % a.shape[1]

print ("value =", a[i,j])
print ("index =", (i,j))

value = 25
index = (2, 2)


In [150]:
np.unravel_index(np.argmax(a), a.shape)


(2, 2)

In [155]:
%%timeit

b = np.random.randint(0, 10, size=(1_000,1_000))
b[36, 42] = 20
b = b.ravel()


13.5 ms ± 108 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [162]:
%%timeit
np.max(b)

6.81 µs ± 25.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [161]:
%%timeit
b1 = b.ravel()
max(b1)

1.62 µs ± 6.53 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [166]:
np.random.seed(32)

a = np.random.randint(0, 10, size = (3,7))
a[1,3] =15

a

array([[ 7,  5,  6,  8,  3,  7,  9],
       [ 3,  5,  9, 15,  1,  3,  1],
       [ 2,  3,  8,  2,  4,  2,  4]])

In [167]:
a.max(axis=0)

array([ 7,  5,  9, 15,  4,  7,  9])

In [169]:

a.sum(axis=1)

array([45, 37, 25])

In [171]:
np.random.seed(8)
a = np.random.randint(0, 10, size = (4,2))
b = np.random.randint(0, 10, size = (4,2))

a, b

(array([[3, 4],
        [1, 9],
        [5, 8],
        [3, 8]]),
 array([[0, 5],
        [1, 3],
        [9, 2],
        [2, 6]]))

In [175]:
a, b, a * b

(array([[3, 4],
        [1, 9],
        [5, 8],
        [3, 8]]),
 array([[0, 5],
        [1, 3],
        [9, 2],
        [2, 6]]),
 array([[ 0, 20],
        [ 1, 27],
        [45, 16],
        [ 6, 48]]))

In [176]:
a, b, a + b

(array([[3, 4],
        [1, 9],
        [5, 8],
        [3, 8]]),
 array([[0, 5],
        [1, 3],
        [9, 2],
        [2, 6]]),
 array([[ 3,  9],
        [ 2, 12],
        [14, 10],
        [ 5, 14]]))

In [178]:
a, b, np.fmax(a, b)

(array([[3, 4],
        [1, 9],
        [5, 8],
        [3, 8]]),
 array([[0, 5],
        [1, 3],
        [9, 2],
        [2, 6]]),
 array([[3, 5],
        [1, 9],
        [9, 8],
        [3, 8]]))

In [179]:
a, b, a > b

(array([[3, 4],
        [1, 9],
        [5, 8],
        [3, 8]]),
 array([[0, 5],
        [1, 3],
        [9, 2],
        [2, 6]]),
 array([[ True, False],
        [False,  True],
        [False,  True],
        [ True,  True]]))

In [183]:
np.random.seed(256)
a = np.random.random(size=(2,5))
b = a + np.random.random(size =(2,5)) * 1e-6
a,b

(array([[0.0457838 , 0.58612071, 0.20323985, 0.08424309, 0.02599218],
        [0.40293724, 0.37871185, 0.05284018, 0.80535711, 0.37964511]]),
 array([[0.04578418, 0.58612146, 0.2032404 , 0.08424361, 0.02599313],
        [0.40293763, 0.37871226, 0.05284059, 0.80535735, 0.37964563]]))

In [184]:
np.isclose(a,b)

array([[ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True]])

In [185]:
np.allclose(a,b)

False

In [189]:
np.random.seed(4)
a = (np.random.random(size=(5, )) - 0.5) * 1e-7

a, np.isclose(a, 0, atol=1e-6)

(array([4.67029839e-08, 4.72322492e-09, 4.72684360e-08, 2.14815994e-08,
        1.97728825e-08]),
 array([ True,  True,  True,  True,  True]))

In [188]:
np.isclose(a, 0, atol=1e-6)

array([ True,  True,  True,  True,  True])

In [190]:
a = np.asarray([ True,  True,  False,  False, True])
a

array([ True,  True, False, False,  True])

In [192]:
a.any(), np.any(a)

(True, True)

In [193]:
a.all(), np.all(a)

(False, False)

In [194]:
a = np.asarray([[ True,  True,  False,  False, True],
                [ True,  False,  False,  True, False]])
a, a.any(axis=0), a.all(axis=1)

(array([[ True,  True, False, False,  True],
        [ True, False, False,  True, False]]),
 array([ True,  True, False,  True,  True]),
 array([False, False]))

In [196]:
np.logical_not(a), ~a

(array([[False, False,  True,  True, False],
        [False,  True,  True, False,  True]]),
 array([[False, False,  True,  True, False],
        [False,  True,  True, False,  True]]))

In [212]:
np.random.seed(256)

a = np.random.randint (-5, 5, size =(5,5))

a, (a == 0).any(axis=1), a[(a == 0).any(axis=1)]

(array([[-5,  2, -4, -5,  4],
        [ 0,  1,  2, -2, -3],
        [ 3,  2, -1,  1, -1],
        [-3, -5,  4,  2,  4],
        [-5, -3, -5,  4,  3]]),
 array([False,  True, False, False, False]),
 array([[ 0,  1,  2, -2, -3]]))

In [204]:
a = np.asarray([ True,  True,  False,  False, True])
b = np.asarray([ True,  False,  False,  True, False])
                
a,b

(array([ True,  True, False, False,  True]),
 array([ True, False, False,  True, False]))

In [205]:
np.logical_and(a,b), a & b

(array([ True, False, False, False, False]),
 array([ True, False, False, False, False]))

In [206]:
np.logical_or(a,b), a | b

(array([ True,  True, False,  True,  True]),
 array([ True,  True, False,  True,  True]))

In [207]:
np.logical_xor(a,b), a ^ b

(array([False,  True, False,  True,  True]),
 array([False,  True, False,  True,  True]))

In [210]:
np.bitwise_and(a,b), a & b
np.bitwise_or(a,b), a | b
np.bitwise_xor(a,b), a ^ b

(array([False,  True, False,  True,  True]),
 array([False,  True, False,  True,  True]))

In [215]:
np.random.seed(256)

a = np.random.randint (-5, 5, size =(5,5))

a, (a == 0).any(axis=1), a[(a == 0).any(axis=1)]

(array([[-5,  2, -4, -5,  4],
        [ 0,  1,  2, -2, -3],
        [ 3,  2, -1,  1, -1],
        [-3, -5,  4,  2,  4],
        [-5, -3, -5,  4,  3]]),
 array([False,  True, False, False, False]),
 array([[ 0,  1,  2, -2, -3]]))

In [218]:
a > 0, a <0

(array([[False,  True, False, False,  True],
        [False,  True,  True, False, False],
        [ True,  True, False,  True, False],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True]]),
 array([[ True, False,  True,  True, False],
        [False, False, False,  True,  True],
        [False, False,  True, False,  True],
        [ True,  True, False, False, False],
        [ True,  True,  True, False, False]]))

In [217]:
a[:, (a > 0).sum(axis=0) > (a < 0).sum(axis=0)]

array([[ 2, -5,  4],
       [ 1, -2, -3],
       [ 2,  1, -1],
       [-5,  2,  4],
       [-3,  4,  3]])

In [242]:
A = np.random.randint(0,5, size=(3,2))
B = np.random.randint(5,10, size=(2,3))

A,B

(array([[4, 0],
        [3, 2],
        [4, 4]]),
 array([[8, 7, 8],
        [9, 9, 6]]))

In [238]:
A@B, np.matmul(A, B)

(array([[52, 40, 40],
        [18, 14, 12],
        [ 9,  7,  6]]),
 array([[52, 40, 40],
        [18, 14, 12],
        [ 9,  7,  6]]))

In [239]:
a = np.random.randint(0,5, size=(4,))
b = np.random.randint(5,10, size=(4,))

a, b 

(array([0, 2, 2, 0]), array([5, 5, 5, 5]))

In [235]:
np.dot(a,b), np.dot(A,B)

(38,
 array([[288,  96, 108],
        [132,  52,  64],
        [ 99,  39,  48]]))

In [243]:
C = np.asmatrix(A)
D = np.matrix(B)
A[0][0] = 12
B[0][0] = 24

C, D

(matrix([[12,  0],
         [ 3,  2],
         [ 4,  4]]),
 matrix([[8, 7, 8],
         [9, 9, 6]]))

In [245]:
F = C * D
F

matrix([[96, 84, 96],
        [42, 39, 36],
        [68, 64, 56]])

In [246]:
A, A**2

(array([[12,  0],
        [ 3,  2],
        [ 4,  4]]),
 array([[144,   0],
        [  9,   4],
        [ 16,  16]], dtype=int32))

In [247]:
F, F **2

(matrix([[96, 84, 96],
         [42, 39, 36],
         [68, 64, 56]]),
 matrix([[19272, 17484, 17616],
         [ 8118,  7353,  7452],
         [13024, 11792, 11968]]))

In [248]:
np.random.seed(512)

A = np.random.randint (0, 5, size =(3,3))

A

array([[3, 1, 2],
       [1, 0, 0],
       [3, 2, 0]])

In [249]:
np.linalg.det(A)

4.0

In [251]:
A1= np.linalg.inv(A)
A1

array([[ 0.  ,  1.  ,  0.  ],
       [ 0.  , -1.5 ,  0.5 ],
       [ 0.5 , -0.75, -0.25]])

In [253]:
A @ A1, A1 @ A


(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [256]:
b = np.array([1,-2,1], dtype=np.float64)
A,b

(array([[3, 1, 2],
        [1, 0, 0],
        [3, 2, 0]]),
 array([ 1., -2.,  1.]))

In [257]:
x = np.linalg.solve(A,b)
x

array([-2.  ,  3.5 ,  1.75])

In [259]:
A @ x - b

array([-8.8817842e-16, -4.4408921e-16, -8.8817842e-16])

In [260]:
Iam, V = np.linalg.eig(A)
Iam, V

(array([ 4.67882303+0.j        , -0.83941152+0.38769081j,
        -0.83941152-0.38769081j]),
 array([[ 0.79497756+0.j        ,  0.45795361+0.13480762j,
          0.45795361-0.13480762j],
        [ 0.16990973+0.j        , -0.38851526-0.34003753j,
         -0.38851526+0.34003753j],
        [ 0.58235845+0.j        , -0.71101039+0.j        ,
         -0.71101039-0.j        ]]))

In [267]:
X = np.array([[3,4], [2,7], [1,5]])
y = np.array([1,4,2])
E = np.eye(2)
lam = 0.01
w = np.linalg.inv(X.T @ X + lam * E) @ X.T @ y
w

array([-0.43950792,  0.61798406])

In [268]:
np.random.rand(10)

array([0.68233647, 0.32597119, 0.67656027, 0.88749116, 0.28003724,
       0.82334775, 0.16825266, 0.54987075, 0.2304416 , 0.99234406])

In [269]:
np.random.randint(0, 10, 10)


array([1, 6, 3, 8, 0, 7, 5, 8, 8, 4])

In [272]:
np.random.permutation(10)

array([1, 5, 0, 7, 8, 9, 4, 3, 2, 6])

In [273]:
np.random.choice(10)

2

In [274]:
np.random.seed(2048)
a = np.random.choice(10, size=(3,10))
a

array([[5, 7, 5, 9, 8, 6, 1, 2, 7, 8],
       [6, 9, 2, 7, 6, 0, 3, 9, 2, 4],
       [9, 1, 8, 3, 5, 2, 1, 0, 5, 6]])

In [275]:
np.sort(a.ravel())

array([0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7,
       7, 8, 8, 8, 9, 9, 9, 9])

In [276]:
a.sort(axis=0)
a

array([[5, 1, 2, 3, 5, 0, 1, 0, 2, 4],
       [6, 7, 5, 7, 6, 2, 1, 2, 5, 6],
       [9, 9, 8, 9, 8, 6, 3, 9, 7, 8]])

In [277]:
a.sort(axis=1)
a

array([[0, 0, 1, 1, 2, 2, 3, 4, 5, 5],
       [1, 2, 2, 5, 5, 6, 6, 6, 7, 7],
       [3, 6, 7, 8, 8, 8, 9, 9, 9, 9]])

In [279]:
np.random.seed(2048)
a = np.random.choice(10, size=(3,10))

a, a.argsort(axis=0), a.argsort(axis=1)


(array([[5, 7, 5, 9, 8, 6, 1, 2, 7, 8],
        [6, 9, 2, 7, 6, 0, 3, 9, 2, 4],
        [9, 1, 8, 3, 5, 2, 1, 0, 5, 6]]),
 array([[0, 2, 1, 2, 2, 1, 0, 2, 1, 1],
        [1, 0, 0, 1, 1, 2, 2, 0, 2, 2],
        [2, 1, 2, 0, 0, 0, 1, 1, 0, 0]], dtype=int64),
 array([[6, 7, 0, 2, 5, 1, 8, 4, 9, 3],
        [5, 2, 8, 6, 9, 0, 4, 3, 1, 7],
        [7, 1, 6, 5, 3, 4, 8, 9, 2, 0]], dtype=int64))

In [280]:
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])